### ISSUE TITLE
hitting weird error on go get

### ISSUE THREAD

**Issue by WLun001** [containerd/console#45]
```
go version
go version go1.15 darwin/amd64
```
```
$ go get -u -v github.com/containerd/console


github.com/containerd/console (download)
github.com/containerd/console
# github.com/containerd/console
go/src/github.com/containerd/console/console_unix.go:31:37: undefined: unix.O_RDWR
go/src/github.com/containerd/console/console_unix.go:31:49: undefined: unix.O_NOCTTY
go/src/github.com/containerd/console/console_unix.go:31:63: undefined: unix.O_CLOEXEC
go/src/github.com/containerd/console/console_unix.go:51:12: undefined: unix.Termios
go/src/github.com/containerd/console/console_unix.go:85:32: undefined: unix.Termios
go/src/github.com/containerd/console/tc_darwin.go:27:13: undefined: unix.TIOCGETA
go/src/github.com/containerd/console/tc_darwin.go:28:13: undefined: unix.TIOCSETA
go/src/github.com/containerd/console/tc_unix.go:25:27: undefined: unix.Termios
go/src/github.com/containerd/console/tc_unix.go:34:27: undefined: unix.Termios
go/src/github.com/containerd/console/tc_unix.go:81:18: undefined: unix.Termios
go/src/github.com/containerd/console/console_unix.go:31:63: too many errors
```

related to https://github.com/gofiber/cli/issues/38

**Comment by thaJeztah** [comment]
What version of golang.org/x/sys did it pick? I think this was fixed by https://github.com/containerd/console/pull/40 (see https://github.com/containerd/console/pull/39)

**Comment by WLun001** [comment]
@thaJeztah How to check?

**Comment by thaJeztah** [comment]
In the project in which you're using this module, you can run something like;

```bash
go list -m all | grep golang.org/x/sys
```

However, if you're running `go get` without go modules (using go path), then it may be that you have an outdated version of `golang.org/x/sys` in your GOPATH, and that it picks that version to build

**Comment by WLun001** [comment]
@thaJeztah thanks! I had to change directory to project with go modules, only it can `go get` successfully.  I just fresh reinstalled Go, and `golang.org/x/sys` is on latest commit, still doesn't work outside go modules.

**Comment by thaJeztah** [comment]
Thanks! Also tried in a container to verify;

```console
$ docker run -it --rm golang:1.14 bash -c 'mkdir /foo && cd /foo && go get -u github.com/gofiber/cli/fiber && fiber --help'

github.com/gofiber/cli (download)
github.com/fsnotify/fsnotify (download)
get "golang.org/x/sys/unix": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
golang.org/x/sys (download)
get "golang.org/x/sys/internal/unsafeheader": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys/internal/unsafeheader?go-get=1
get "golang.org/x/sys/internal/unsafeheader": verifying non-authoritative meta tag
github.com/charmbracelet/bubbles (download)
github.com/charmbracelet/bubbletea (download)
github.com/containerd/console (download)
github.com/muesli/termenv (download)
github.com/lucasb-eyer/go-colorful (download)
github.com/mattn/go-isatty (download)
github.com/mattn/go-runewidth (download)
get "golang.org/x/crypto/ssh/terminal": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at //golang.org/x/crypto/ssh/terminal?go-get=1
get "golang.org/x/crypto/ssh/terminal": verifying non-authoritative meta tag
golang.org/x/crypto (download)
get "golang.org/x/term": found meta tag get.metaImport{Prefix:"golang.org/x/term", VCS:"git", RepoRoot:"https://go.googlesource.com/term"} at //golang.org/x/term?go-get=1
golang.org/x/term (download)
github.com/atotto/clipboard (download)
github.com/spf13/cobra (download)
github.com/spf13/pflag (download)
golang.org/x/sys/internal/unsafeheader
github.com/containerd/console/vendor/golang.org/x/sys/internal/unsafeheader
github.com/mattn/go-runewidth
github.com/lucasb-eyer/go-colorful
github.com/containerd/console/vendor/golang.org/x/sys/unix
golang.org/x/sys/unix
github.com/atotto/clipboard
github.com/spf13/pflag
github.com/fsnotify/fsnotify
github.com/mattn/go-isatty
github.com/muesli/termenv
github.com/containerd/console
golang.org/x/term
github.com/spf13/cobra
golang.org/x/crypto/ssh/terminal
github.com/charmbracelet/bubbletea
github.com/charmbracelet/bubbles/spinner
github.com/charmbracelet/bubbles/textinput
github.com/gofiber/cli/cmd/internal
github.com/gofiber/cli/cmd
github.com/gofiber/cli/fiber

🚀 Fiber is an Express inspired web framework written in Go with 💖
Learn more on https://gofiber.io

CLI version 0.0.6

Usage:
  fiber [flags]
  fiber [command]

Available Commands:
  dev         Rerun the fiber project if watched files changed
  help        Help about any command
  new         Generate a new fiber project
  upgrade     Upgrade Fiber cli if a newer version is available
  version     Print the local and released version number of fiber

Flags:
  -h, --help   help for fiber

Use "fiber [command] --help" for more information about a command.
```


I did see a possible bug in the fiber code; trying to run `fiber version` after that prints an error;

```
fiber version: open go.mod: no such file or directory (latest 2.2.0)
```

**Comment by thaJeztah** [comment]
Let me close this one

**Comment by kiyonlin** [comment]
> I did see a possible bug in the fiber code; trying to run fiber version after that prints an error;
> 
> ```
> fiber version: open go.mod: no such file or directory (latest 2.2.0)
> ```

@thaJeztah Actually the output is expected 😄 
`fiber version` prints the local(version in go module project) and released version number of fiber

**Comment by thaJeztah** [comment]
@kiyonlin right, but wondering why it didn't find the `go.mod` during compile; is it looking in the wrong location if it's fetched when go modules are enabled?

**Comment by kiyonlin** [comment]
@thaJeztah That's maybe because `fiber version`  only finds `go.mod` in current working directory.

**Comment by thaJeztah** [comment]
oh, it tries at _runtime_ not during compile? 🤔
